export type ProductCategory =
  | "power-wheelchairs"
  | "manual-wheelchairs"
  | "seating-positioning"
  | "power-scooters"
  | "walkers-rollators"
  | "transfer-aids"
  | "accessories";

export interface Product {
  slug: string;
  name: string;
  brand: string;
  category: ProductCategory;
  categoryLabel: string;
  tagline: string;
  image: string;
  priceRange: string;
  price?: number;
  requiresConsultation: boolean;
  isFeatured?: boolean;
  badges: string[];
  goodFor: string[];
  notIdealFor: string[];
  specs: { label: string; value: string }[];
  description: string;
  crtRequired: boolean;
}

export const products: Product[] = [
  {
    slug: "permobil-m3-corpus",
    name: "Permobil M3 Corpus",
    brand: "Permobil",
    category: "power-wheelchairs",
    categoryLabel: "Power Wheelchairs",
    tagline: "Advanced power chair for full-time users with complex seating needs",
    image: "https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=600&q=80&fit=crop",
    priceRange: "Contact for Quote",
    requiresConsultation: true,
    isFeatured: true,
    badges: ["CRT Required", "Insurance Eligible"],
    goodFor: ["Users with limited upper body strength","Indoor and outdoor environments","Those needing custom seating","Full-time power chair users"],
    notIdealFor: ["Occasional users","Those who can self-propel manually"],
    specs: [
      { label: "Drive System", value: "Rear-wheel drive" },
      { label: "Max Speed", value: "6 mph" },
      { label: "Range", value: "Up to 15 miles" },
      { label: "Weight Capacity", value: "300 lbs" },
      { label: "Seating", value: "Corpus 3D (custom)" },
    ],
    description: "The Permobil M3 Corpus is a rear-wheel drive power wheelchair designed for individuals with complex seating needs. It pairs the M3 power base with the Corpus 3D seating system, which can be custom-configured by our certified ATPs to match your exact body dimensions and functional goals. Medicare and most private insurance plans cover this chair with proper clinical documentation.",
    crtRequired: true,
  },
  {
    slug: "quickie-q50-r",
    name: "Quickie Q50 R",
    brand: "Quickie",
    category: "power-wheelchairs",
    categoryLabel: "Power Wheelchairs",
    tagline: "Rehab-grade rear-wheel drive with 40-degree tilt and full electronics",
    image: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=600&q=80&fit=crop",
    priceRange: "Contact for Quote",
    requiresConsultation: true,
    isFeatured: true,
    badges: ["CRT Required", "Insurance Eligible"],
    goodFor: ["Active community users","Outdoor and indoor use","Those needing tilt-in-space positioning","Users with progressive conditions"],
    notIdealFor: ["Tight indoor spaces only","Users who require minimal support"],
    specs: [
      { label: "Drive System", value: "Rear-wheel drive" },
      { label: "Tilt Range", value: "0–40 degrees" },
      { label: "Max Speed", value: "6.2 mph" },
      { label: "Weight Capacity", value: "275 lbs" },
      { label: "Electronics", value: "Q-Logic 3" },
    ],
    description: "The Quickie Q50 R delivers robust rear-wheel drive performance with 40 degrees of power tilt for pressure relief and positioning. The Q-Logic 3 electronics system supports proportional joystick, head array, and sip-and-puff access. Covered by Medicare Part B with completed clinical evaluation and Letter of Medical Necessity.",
    crtRequired: true,
  },
  {
    slug: "tilite-aero-z",
    name: "TiLite Aero Z",
    brand: "TiLite",
    category: "manual-wheelchairs",
    categoryLabel: "Manual Wheelchairs",
    tagline: "Custom titanium ultralight frame built to your exact measurements",
    image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=600&q=80&fit=crop",
    priceRange: "Contact for Quote",
    requiresConsultation: true,
    isFeatured: true,
    badges: ["CRT Required", "Ultralight", "Custom Fit"],
    goodFor: ["Active manual wheelchair users","Those who self-propel regularly","Individuals needing a custom-fit frame","Users who travel frequently"],
    notIdealFor: ["Users who cannot self-propel","Those requiring power mobility"],
    specs: [
      { label: "Frame Material", value: "Aerospace titanium" },
      { label: "Frame Weight", value: "From 14 lbs" },
      { label: "Folding", value: "Rigid (non-folding)" },
      { label: "Customization", value: "Full — width, depth, height, camber" },
      { label: "Warranty", value: "Lifetime frame" },
    ],
    description: "The TiLite Aero Z is a fully custom rigid titanium ultralight manual wheelchair. Every frame is built to the user's exact body measurements and functional goals, configured by our certified ATPs in collaboration with your OT. Titanium construction gives a lifetime frame warranty and exceptional durability at minimum weight. Covered under Medicare K0005 (ultralightweight manual wheelchair) with documentation.",
    crtRequired: true,
  },
  {
    slug: "roho-quadtro-select",
    name: "ROHO Quadtro Select",
    brand: "ROHO",
    category: "seating-positioning",
    categoryLabel: "Seating & Positioning",
    tagline: "Air-cell cushion for pressure injury prevention",
    image: "https://images.unsplash.com/photo-1584145798265-b286d367426f?w=600&q=80&fit=crop",
    priceRange: "Contact for Quote",
    requiresConsultation: false,
    badges: ["Insurance Eligible"],
    goodFor: ["Users at risk for pressure injuries","Long daily sitting time","Post-surgical recovery","Skin integrity concerns"],
    notIdealFor: ["Users who are ambulatory most of the day","Occasional wheelchair users"],
    specs: [
      { label: "Cell Type", value: "Independent air cells" },
      { label: "Zones", value: "4 independently adjustable" },
      { label: "Cover", value: "Stretch-air fabric" },
      { label: "Sizes", value: "14–22 inch widths" },
      { label: "Warranty", value: "2 years" },
    ],
    description: "The ROHO Quadtro Select uses individual air cells to offload pressure across bony prominences. Proper inflation and fit are essential — our team sets this up as part of your seating evaluation.",
    crtRequired: false,
  },
  {
    slug: "pride-go-go-elite",
    name: "Pride Go-Go Elite Traveller",
    brand: "Pride",
    category: "power-scooters",
    categoryLabel: "Power Scooters",
    tagline: "Lightweight travel scooter for everyday independence",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80&fit=crop",
    priceRange: "$1,200 – $1,800",
    price: 1500,
    requiresConsultation: false,
    isFeatured: false,
    badges: ["Ready to Ship"],
    goodFor: ["Short-distance community errands","Travel and airports","Shopping and outings","Users with mild mobility limitations"],
    notIdealFor: ["Full-time mobility users","Rough terrain","Users needing custom seating support"],
    specs: [
      { label: "Drive", value: "3-wheel" },
      { label: "Weight", value: "46 lbs (heaviest piece)" },
      { label: "Max Speed", value: "4 mph" },
      { label: "Range", value: "Up to 8 miles" },
      { label: "Weight Capacity", value: "300 lbs" },
    ],
    description: "The Pride Go-Go Elite Traveller disassembles into 5 lightweight pieces, making it the preferred choice for air travel and everyday errands. Feather-touch disassembly, automatic feathering, and anti-tip wheels. No consultation required — ships within 3–5 business days.",
    crtRequired: false,
  },
  {
    slug: "drive-nitro-rollator",
    name: "Drive Nitro Euro Style Rollator",
    brand: "Drive Medical",
    category: "walkers-rollators",
    categoryLabel: "Walkers & Rollators",
    tagline: "Sleek, lightweight rollator for active users",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&q=80&fit=crop",
    priceRange: "$180 – $240",
    price: 210,
    requiresConsultation: false,
    badges: ["Ready to Ship", "Lightweight"],
    goodFor: ["Active older adults","Indoor and outdoor use","Users needing walking support","Those who walk long distances"],
    notIdealFor: ["Users needing full weight bearing support","Those with severe balance issues"],
    specs: [
      { label: "Frame", value: "Aluminum" },
      { label: "Weight", value: "13 lbs" },
      { label: "Seat Height", value: "21–23 inches" },
      { label: "Weight Capacity", value: "300 lbs" },
      { label: "Folding", value: "Yes — loop-lock" },
    ],
    description: "The Drive Nitro Euro features loop-lock brakes, a padded seat, and a large underseat bag. The European frame design is narrower than standard rollators, making it ideal for indoor use and tight spaces. Ships within 2–3 business days.",
    crtRequired: false,
  },
  {
    slug: "pride-jazzy-ultra-light",
    name: "Pride Jazzy Ultra Light",
    brand: "Pride",
    category: "power-wheelchairs",
    categoryLabel: "Power Wheelchairs",
    tagline: "Foldable carbon fiber power chair — lightest in its class",
    image: "https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=600&q=80&fit=crop",
    priceRange: "$3,200 – $3,600",
    price: 3400,
    requiresConsultation: false,
    isFeatured: true,
    badges: ["Ready to Ship"],
    goodFor: ["Active users who travel frequently","Those needing a foldable power chair","Users with moderate mobility needs","Air travel compatible"],
    notIdealFor: ["Heavy outdoor terrain","Users needing complex seating","Full-time power chair users with high support needs"],
    specs: [
      { label: "Frame", value: "Carbon fiber" },
      { label: "Weight", value: "43.5 lbs" },
      { label: "Folding", value: "Yes — auto-fold" },
      { label: "Max Speed", value: "4 mph" },
      { label: "Range", value: "Up to 15.5 miles" },
      { label: "Weight Capacity", value: "300 lbs" },
    ],
    description: "The Pride Jazzy Ultra Light is the world's first carbon-fiber folding power wheelchair. At 43.5 lbs, it's FAA-compliant for air travel and folds automatically at the press of a button. Ideal for users who want the independence of a power chair with the portability of a manual wheelchair.",
    crtRequired: false,
  },
  {
    slug: "golden-ally-gp303",
    name: "Golden Ally GP303",
    brand: "Golden",
    category: "power-wheelchairs",
    categoryLabel: "Power Wheelchairs",
    tagline: "Smart app-connected power chair for independent living",
    image: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=600&q=80&fit=crop",
    priceRange: "$3,800 – $4,400",
    price: 4090,
    requiresConsultation: false,
    isFeatured: true,
    badges: ["Ready to Ship", "Insurance Eligible"],
    goodFor: ["Tech-forward users","Indoor and outdoor use","Those who want smartphone connectivity","Users with moderate mobility limitations"],
    notIdealFor: ["Complex seating needs","Very tight indoor spaces","Users needing CRT-level clinical support"],
    specs: [
      { label: "Drive", value: "Rear-wheel drive" },
      { label: "Max Speed", value: "5 mph" },
      { label: "Range", value: "Up to 18 miles" },
      { label: "Weight Capacity", value: "300 lbs" },
      { label: "Connectivity", value: "Bluetooth app" },
    ],
    description: "The Golden Ally GP303 pairs power chair performance with smart app control via Bluetooth. Adjust speed, lock/unlock, and monitor battery from your phone. Shipping in 5–7 business days.",
    crtRequired: false,
  },
  {
    slug: "pride-go-go-carbon-sc25",
    name: "Pride Go-Go Carbon SC25",
    brand: "Pride",
    category: "power-scooters",
    categoryLabel: "Power Scooters",
    tagline: "Foldable carbon fiber scooter — airline approved",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80&fit=crop",
    priceRange: "$3,500 – $3,950",
    price: 3720,
    requiresConsultation: false,
    badges: ["Ready to Ship"],
    goodFor: ["Frequent travelers","Users needing a portable scooter","Those needing airline-approved mobility","Active community users"],
    notIdealFor: ["Heavy-duty outdoor terrain","Users with high support needs","Full-time mobility users"],
    specs: [
      { label: "Frame", value: "Carbon fiber" },
      { label: "Weight", value: "37.5 lbs" },
      { label: "Max Speed", value: "3.7 mph" },
      { label: "Range", value: "Up to 9.3 miles" },
      { label: "Weight Capacity", value: "265 lbs" },
    ],
    description: "The Pride Go-Go Carbon SC25 is the lightest folding scooter in its class. FAA-compliant lithium battery, auto-fold, and under 38 lbs. Perfect for travelers who want full mobility independence wherever they go.",
    crtRequired: false,
  },
  {
    slug: "amylior-gs100",
    name: "Amylior GS 100",
    brand: "Amylior",
    category: "power-scooters",
    categoryLabel: "Power Scooters",
    tagline: "Compact indoor-outdoor scooter with S-Drive control system",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80&fit=crop",
    priceRange: "$1,700 – $2,100",
    price: 1895,
    requiresConsultation: false,
    badges: ["Ready to Ship"],
    goodFor: ["Indoor and outdoor use","Tight corridors","Community errands","Users with moderate mobility needs"],
    notIdealFor: ["Rough terrain","Heavy outdoor trails","Users with high support needs"],
    specs: [
      { label: "Drive", value: "4-wheel" },
      { label: "Max Speed", value: "5 mph" },
      { label: "Range", value: "Up to 22 miles" },
      { label: "Weight Capacity", value: "330 lbs" },
      { label: "Turning Radius", value: "21 inches" },
    ],
    description: "The Amylior GS 100 features the S-Drive proportional control system for precise steering and smooth transitions. The 4-wheel base provides excellent stability indoors and on paved surfaces. High weight capacity and long range make it a reliable daily driver.",
    crtRequired: false,
  },
  {
    slug: "drive-blue-streak",
    name: "Drive Blue Streak",
    brand: "Drive Medical",
    category: "manual-wheelchairs",
    categoryLabel: "Manual Wheelchairs",
    tagline: "Reliable, affordable manual wheelchair for everyday use",
    image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=600&q=80&fit=crop",
    priceRange: "$380 – $480",
    price: 425,
    requiresConsultation: false,
    badges: ["Ready to Ship"],
    goodFor: ["Occasional and daily users","Indoor use","Budget-conscious buyers","Temporary or post-surgical use"],
    notIdealFor: ["Full-time self-propellers","Active outdoor users","Users needing custom fitting"],
    specs: [
      { label: "Frame", value: "Steel cross-brace" },
      { label: "Seat Width", value: "16, 18, 20 inch options" },
      { label: "Weight", value: "36 lbs" },
      { label: "Weight Capacity", value: "250 lbs" },
      { label: "Footrests", value: "Swing-away, removable" },
    ],
    description: "The Drive Blue Streak is a no-frills, well-built manual wheelchair for everyday use. Cross-brace frame folds flat for transport, swing-away footrests for easy transfers. Available in 3 seat widths. Ships in 2–3 business days.",
    crtRequired: false,
  },
  {
    slug: "humancare-nexus3",
    name: "HumanCare neXus 3 Rollator",
    brand: "HumanCare",
    category: "walkers-rollators",
    categoryLabel: "Walkers & Rollators",
    tagline: "Cable-free locking brakes for a cleaner, safer rollator experience",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&q=80&fit=crop",
    priceRange: "$350 – $450",
    price: 398,
    requiresConsultation: false,
    badges: ["Ready to Ship"],
    goodFor: ["Users who want reliable braking","Indoor and outdoor use","Active older adults","Users who travel"],
    notIdealFor: ["Users with severe balance impairments","Very rough terrain"],
    specs: [
      { label: "Brake System", value: "Cable-free" },
      { label: "Frame", value: "Aluminum" },
      { label: "Weight", value: "14 lbs" },
      { label: "Seat Height", value: "Adjustable" },
      { label: "Weight Capacity", value: "300 lbs" },
    ],
    description: "The HumanCare neXus 3 replaces traditional brake cables with an internal mechanism — no exposed cables, no snags, no maintenance. The result is a cleaner-looking, more reliable rollator for active daily use.",
    crtRequired: false,
  },
  {
    slug: "bios-deluxe-folding-walker",
    name: "BIOS Deluxe Folding Walker",
    brand: "BIOS",
    category: "walkers-rollators",
    categoryLabel: "Walkers & Rollators",
    tagline: "Lightweight 2-wheel walker for those who need basic stability support",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&q=80&fit=crop",
    priceRange: "$90 – $130",
    price: 110,
    requiresConsultation: false,
    badges: ["Ready to Ship"],
    goodFor: ["Post-surgical recovery","Users with mild balance issues","Indoor use","Budget walkers"],
    notIdealFor: ["Outdoor terrain","Users who need to rest frequently","Those needing a seat"],
    specs: [
      { label: "Weight", value: "5.5 lbs" },
      { label: "Weight Capacity", value: "350 lbs" },
      { label: "Height Range", value: "32–38 inches" },
      { label: "Folding", value: "Yes" },
      { label: "Front Wheels", value: "5-inch swivel" },
    ],
    description: "The BIOS Deluxe Folding Walker is the lightest full-size walker in our catalog. Front wheels reduce friction for smooth indoor movement. Folds flat for transport and storage. Ships same-day.",
    crtRequired: false,
  },
  {
    slug: "drive-balanced-aire",
    name: "Drive Balanced Aire Cushion",
    brand: "Drive Medical",
    category: "seating-positioning",
    categoryLabel: "Seating & Positioning",
    tagline: "Alternating air-cell cushion for active pressure management",
    image: "https://images.unsplash.com/photo-1584145798265-b286d367426f?w=600&q=80&fit=crop",
    priceRange: "$350 – $440",
    price: 395,
    requiresConsultation: false,
    badges: ["Insurance Eligible"],
    goodFor: ["Long daily sitting","Users with existing pressure injuries","High-risk skin integrity patients","Post-surgical seating"],
    notIdealFor: ["Occasional sitters","Active self-propellers who need a firm base"],
    specs: [
      { label: "Cell Type", value: "Alternating air cells" },
      { label: "Zones", value: "2-zone adjustment" },
      { label: "Cover", value: "Non-slip base" },
      { label: "Sizes", value: "16–20 inch widths" },
      { label: "Warranty", value: "1 year" },
    ],
    description: "The Drive Balanced Aire provides alternating pressure through a two-zone air cell system. Designed for users at elevated risk for pressure injuries, this cushion actively redistributes pressure and can be covered by insurance with documentation.",
    crtRequired: false,
  },
  {
    slug: "bios-coccyx-gel",
    name: "BIOS Coccyx Gel Cushion",
    brand: "BIOS",
    category: "seating-positioning",
    categoryLabel: "Seating & Positioning",
    tagline: "Coccyx cut-out gel cushion for tailbone and lower back relief",
    image: "https://images.unsplash.com/photo-1584145798265-b286d367426f?w=600&q=80&fit=crop",
    priceRange: "$60 – $100",
    price: 79,
    requiresConsultation: false,
    badges: ["Ready to Ship"],
    goodFor: ["Tailbone pain or injury","Long sitting in standard chairs","Office workers with mobility needs","Post-surgical coccyx recovery"],
    notIdealFor: ["High-risk pressure injury patients","Full-time wheelchair users"],
    specs: [
      { label: "Material", value: "Gel + foam combination" },
      { label: "Cut-out", value: "Coccyx and tailbone" },
      { label: "Cover", value: "Removable, washable" },
      { label: "Size", value: "17 x 15 inches" },
      { label: "Warranty", value: "90 days" },
    ],
    description: "The BIOS Coccyx Gel Cushion combines a memory foam base with a gel top layer, shaped with a rear cut-out to eliminate direct pressure on the coccyx. Ships same-day. Budget-friendly entry point for pressure management.",
    crtRequired: false,
  },
  {
    slug: "drive-transfer-bench",
    name: "Drive Folding Sliding Transfer Bench",
    brand: "Drive Medical",
    category: "transfer-aids",
    categoryLabel: "Transfer Aids",
    tagline: "Sliding bath transfer bench for safe bathtub entry and exit",
    image: "https://images.unsplash.com/photo-1584998604882-94bf3d6e3b0e?w=600&q=80&fit=crop",
    priceRange: "$290 – $360",
    price: 320,
    requiresConsultation: false,
    badges: ["Ready to Ship"],
    goodFor: ["Bathtub transfers","Users with limited leg lift","Post-surgical lower limb recovery","Caregivers assisting with bathing"],
    notIdealFor: ["Walk-in shower users","Users who require ceiling lift transfer"],
    specs: [
      { label: "Material", value: "Anodized aluminum" },
      { label: "Seat", value: "Sliding seat with backrest" },
      { label: "Weight Capacity", value: "400 lbs" },
      { label: "Height Range", value: "Adjustable legs" },
      { label: "Folding", value: "Yes" },
    ],
    description: "The Drive Folding Sliding Transfer Bench straddles the bathtub edge, allowing users to sit outside the tub and slide across safely. The sliding seat and 400 lb capacity make it suitable for a wide range of users. Ships within 2–3 business days.",
    crtRequired: false,
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Sandra M.",
    role: "Power chair user — Los Angeles, CA",
    rating: 5,
    quote: "After two years of fighting with my old supplier, Blue Bay got my Permobil approved in 6 weeks. They handled everything — I just showed up for the fitting.",
  },
  {
    id: 2,
    name: "Dr. Rachel Torres",
    role: "Occupational Therapist — Orange County, CA",
    rating: 5,
    quote: "I've referred over a dozen patients to Blue Bay. Their ATPs are credentialed, their documentation is thorough, and my patients always come back satisfied.",
  },
  {
    id: 3,
    name: "James H.",
    role: "Caregiver — San Diego, CA",
    rating: 5,
    quote: "My father needed a power chair but we had no idea where to start. Blue Bay walked us through every step, including insurance. We felt supported the entire time.",
  },
  {
    id: 4,
    name: "Maria L.",
    role: "Manual chair user — Anaheim, CA",
    rating: 5,
    quote: "The TiLite they ordered for me fits perfectly. The evaluation was thorough and they clearly knew what they were doing. Completely different experience from anywhere else I tried.",
  },
];

export const trustStats = [
  { value: 22, suffix: "+", label: "Years of experience" },
  { value: 5000, suffix: "+", label: "Clients served" },
  { value: 98, suffix: "%", label: "Insurance verified" },
  { value: 48, suffix: "hr", label: "Quote turnaround" },
];

export const trackingSteps = [
  { id: 1, label: "Referral Received",       desc: "Your request has been received and assigned to a specialist." },
  { id: 2, label: "Insurance Verification",  desc: "We are verifying your coverage and benefits." },
  { id: 3, label: "Clinical Evaluation",     desc: "Your ATP evaluation has been scheduled or completed." },
  { id: 4, label: "Equipment Order",         desc: "Your equipment has been ordered from the manufacturer." },
  { id: 5, label: "Custom Build",            desc: "Your equipment is being configured to your specifications." },
  { id: 6, label: "Delivery",                desc: "Your equipment is ready and delivery has been scheduled." },
];

export const brands = [
  "Permobil","Quantum Rehab","Pride Mobility","Ki Mobility","Sunrise Medical",
  "Motion Composites","Bruno","Amylior","Motion Concepts","Power Plus Mobility",
  "Travel Buggy","Blake Medical",
];

export const categoryLabels: Record<string, string> = {
  "power-wheelchairs": "Power Wheelchairs",
  "manual-wheelchairs": "Manual Wheelchairs",
  "seating-positioning": "Seating & Positioning",
  "power-scooters": "Power Scooters",
  "walkers-rollators": "Walkers & Rollators",
  "transfer-aids": "Transfer Aids",
  "accessories": "Accessories",
};
